sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      - xsltproc
      - libsaxonb-java
install:
  - ./scripts/setup
script:
  - ./scripts/test
notifications:
  email: false
