language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install xsltproc
  - pip install lxml
install:
  - python setup.py develop
script:
  - python setup.py test
notifications:
  email: false
